version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartassistant
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  flask:
    build:
      context: ./flask_service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/smartassistant?sslmode=disable
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"

  go:
    build:
      context: .
      dockerfile: Dockerfile.go
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/smartassistant?sslmode=disable
      FLASK_URL: http://flask:5000
      PORT: 8080
    depends_on:
      - db
      - flask
    ports:
      - "8080:8080"

volumes:
  dbdata:
