INSERT INTO qa_pairs (question, answer) VALUES
('What are your support hours?', 'Our support hours are 9am–6pm PT, Monday to Friday.'),
('How do I reset my password?', 'Use the “Forgot password” link on the login page and follow the instructions.'),
('What is the refund policy?', 'Refunds are processed within 5 business days for eligible requests.'),
('How can I contact support?', 'Email support@company.com or use the Help Center to submit a ticket.'),
('Do you offer a free trial?', 'Yes, we offer a 14‑day free trial with full features and no credit card required.'),
('Which payment methods are accepted?', 'We accept major credit cards and ACH transfers.'),
('When am I billed?', 'Subscriptions are billed at the start of each monthly cycle unless otherwise specified.'),
('Can I cancel anytime?', 'Yes. You can cancel from the billing settings. Your plan remains active until the end of the current period.'),
('Do you charge sales tax or VAT?', 'Applicable taxes are calculated at checkout based on your billing address.'),
('How do I update my billing details?', 'Go to Settings → Billing to update payment method and invoice information.'),
('Where can I download invoices?', 'Invoices are available under Settings → Billing → Invoices and are emailed to the billing contact.'),
('Do you have an SLA?', 'Yes. Our standard SLA targets 99.9% monthly uptime with defined response times by priority.'),
('Where is your status page?', 'Visit status.company.com for real‑time uptime and incident history.'),
('How do you handle data backups?', 'We perform daily encrypted backups with a 30‑day retention policy.'),
('Is my data encrypted?', 'Yes. Data is encrypted in transit (TLS 1.2+) and at rest (AES‑256).'),
('Are you SOC 2 compliant?', 'Yes. We maintain SOC 2 Type II controls and undergo annual audits.'),
('Do you support GDPR compliance?', 'We act as a data processor and support GDPR rights including data export and deletion on request.'),
('How can I export my data?', 'Use Settings → Data Export to download CSV or JSON exports of your records.'),
('Is there an API?', 'Yes. Our REST API is documented at developer.company.com with OAuth 2.0 authentication.'),
('What are the API rate limits?', 'Default limits are 300 requests per minute per token. Contact support for higher quotas.'),
('How do I enable MFA?', 'Enable multi‑factor authentication from Settings → Security using an authenticator app.'),
('What are your password requirements?', 'Minimum 12 characters with a mix of letters, numbers, or symbols. Passphrases are encouraged.'),
('Do you offer SSO?', 'Yes. We support SAML 2.0 and OpenID Connect for enterprise SSO.'),
('What is the onboarding timeline?', 'Most teams are fully onboarded within 1–2 weeks with guided sessions available.'),
('How can I submit a feature request?', 'Use the in‑app Feedback portal or email product@company.com with details and use cases.');
